FROM phusion/baseimage:bionic-1.0.0

RUN apt-get update
RUN apt-get install -y letsencrypt

#COPY ./scripts/renew-cert.sh /renew-cert.sh
#COPY ./scripts/entrypoint.sh /entrypoint.sh
#
#ENTRYPOINT ["/entrypoint.sh"]